# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-service-handlaggning
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

#Deserializer
mp.messaging.incoming.handlaggning-responses.value.deserializer=se.fk.github.rimfrost.handlaggning.presentation.kafka.HandlaggningResponseMessagePayloadDeserializer

#Serializer
mp.messaging.outgoing.handlaggning-requests.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.handlaggning-done.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

#Incoming
mp.messaging.incoming.handlaggning-responses.connector=smallrye-kafka
mp.messaging.incoming.handlaggning-responses.topic=handlaggning-responses
mp.messaging.incoming.handlaggning-responses.auto.offset.reset=earliest

#Outgoing
mp.messaging.outgoing.handlaggning-requests.connector=smallrye-kafka
mp.messaging.outgoing.handlaggning-done.connector=smallrye-kafka
mp.messaging.outgoing.handlaggning-done.topic=handlaggning-done

%dev.quarkus.kafka.devservices.enabled=true
