quarkus.index-dependency.rimfrost-service-handlaggning-openapi-jaxrs-spec.group-id=se.fk.rimfrost
quarkus.index-dependency.rimfrost-service-handlaggning-openapi-jaxrs-spec.artifact-id=rimfrost-service-handlaggning-openapi-jaxrs-spec

# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-service-handlaggning
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

quarkus.jackson.write-dates-as-timestamps=false

quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true
