# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-service-handlaggning
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

quarkus.jackson.write-dates-as-timestamps=false